version: "3.7"
services:
  db:
    container_name: mysql_db
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=delivery
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
  app:
    container_name: sleung_delivery
    image: sleung_delivery:latest
    depends_on:
      - db
    links:
      - db
    ports:
      - '8080:8080'
    expose:
      - '8080'
    environment:
      - APP_PORT=8080
      - DB_HOST=mysql_db
      - DB_USER=root
      - DB_PASS=rootpass
      - DB_NAME=delivery
      - MAX_UPLOAD_SIZE=1048576
      - GOOGLE_API_KEY=AIzaSyD8ude-PRd-x537MVEiVf3qJhUO19oUA30
      - app-logs:/app/logs
volumes:
  db-data:
  app-logs:
