version: "3.7"
services:
  db:
    container_name: mysql_db
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
  app:
    container_name: sleung_delivery
    image: sleung_delivery:latest
    depends_on:
      - db
    links:
      - db
    ports:
      - '${APP_PORT}:${APP_PORT}'
    expose:
      - '${APP_PORT}'
    environment:
      - APP_PORT=${APP_PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - MAX_UPLOAD_SIZE=${MAX_UPLOAD_SIZE}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - app-logs:/app/logs
volumes:
  db-data:
  app-logs:
