version: "3.7"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=delivery
      - MYSQL_MAX_ALLOWED_PACKET=1024M
      - MYSQL_INNODB_BUFFER_POOL_SIZE=1G
      - MYSQL_INNODB_LOG_FILE_SIZE=256M
      - MYSQL_INNODB_LOG_BUFFER_SIZE=256M
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-data:/var/lib/mysql
  app:
    image: sleung_delivery:latest
    ports:
      - '8080:8080'
    expose:
      - '8080'
    environment:
      - APP_PORT=8080
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASS=pass
      - DB_NAME=delivery
      - MAX_UPLOAD_SIZE=1048576
      - GOOGLE_API_KEY=AIzaSyAtYsSCoET8Y2rk9w3_yDMqw4j5JUBYZbw
      - app-logs:/app/logs
    depends_on:
      - db
volumes:
  db-data: {}
  app-logs: